<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $table = 'user';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function search_default_data($user){
        $this->db->select('*');
        $this->db->from('data');
        $this->db->where("id_user=(select id from user where username='".$user."') and default=1");
        return $this->db->get()->result();
    }

    function search_data($id){
        $this->db->select('*');
        $this->db->from('data');
        $this->db->where("id=$id");
        return $this->db->get()->result();
    }

    function search_family_data($user){
        $this->db->select('*');
        $this->db->from('data');
        $this->db->where("data.id_parent=(select id from data where data.id_user=(select id from user where user.username='".$user."') and data.default=1)");
        $this->db->order_by('data.hubungan','desc');
        return $this->db->get()->result();
    }

    function periksa($user){
        $this->db->select("username");
        $this->db->from("user");
        $this->db->where("username='".$user."'");
        return $this->db->get()->num_rows();
    }
    function periksa2($user,$pass){
        $this->db->select("*");
        $this->db->from("user");
        $this->db->where("username='".$user."' and password = md5('".$pass."')");
        return $this->db->get()->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_by_user($user)
    {
        $this->db->select('id');
        $this->db->where("username='$user'");
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('username', $q);
        $this->db->or_like('password', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('username', $q);
        $this->db->or_like('password', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-21 12:16:53 */
/* http://harviacode.com */